server:
  port: 7128
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finsmart
    username: postgres
    password: ilovecookie
logging:
  level:
    org:
      springframework:
        security: DEBUG
security:
  jwt:
    secret-key: mysecretkey